security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User: 
            algorithm: bcrypt
    providers:
        users_db_provider:
            entity:
                class: App\Entity\User
                property: username
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                entry_point:
                    app.security.login_form_authenticator
                authenticators:
                    - app.security.login_form_authenticator
                    - google_authenticator
                    - facebook_authenticator
            provider: users_db_provider
            logout:
                path: /logout
                target: /
            access_denied_handler: App\Security\AccessDeniedHandler
            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
